### ISSUE TITLE
What domains/urls are blocked?

### ISSUE THREAD

**Issue by XEVMERSHALL** [iamashley0/discord-desktop#16]
I'd prefer to use discord within the browser, so if there is some to get this running with ublock origin.
I'd like to know

**Comment by KorbsStudio** [comment]
It is possible to install Chrome extensions on ElectronJS apps, but from the looks of it Discord Unspy does not use that method to block trackers. 

If you're interested in building a Discord client with Ublock Orgin built-in, considering looking at ElectronJS documentation on installing extensions: https://www.electronjs.org/docs/latest/api/extensions

I've tested this and getting extensions in ElectronJS does work.

**Comment by KorbsStudio** [comment]
@ashley0143 Hey, what URLs are we exactly blocking in Discord Unspy?

**Comment by ghost** [comment]
Hey @XEVMERSHALL, I've rechecked the source code. We're using the adblocker-electron package by Cliqz: https://www.npmjs.com/package/@cliqz/adblocker-electron.

https://easylist.to/easylist/easylist.txt
